language: php

php:
	- 5.4
	- 5.5

before_install:
 - ./unit-tests/ci/install_prereqs.sh
 
before_script:
 	- git submodule --quiet update --init --recursive
 	- (cd ext; export CFLAGS="-g3 -O1 -std=gnu90 -Wall"; phpize && ./configure --enable-phalcon && make --silent -j4 && sudo make --silent install && phpenv config-add ../unit-tests/ci/feathers.ini)
 	- ulimit -c unlimited || true

 script:
 	- ZEND_DONT_UNLOAD_MODULES=1 $(phpenv which php) ./unit-tests/ci/phpunit.php --debug -c unit-tests/phpunit.xml --testsuite=stable
 	- ZEND_DONT_UNLOAD_MODULES=1 PHALCON_NO_RVO=1 $(phpenv which php) ./unit-tests/ci/phpunit.php --debug -c unit-tests/phpunit.xml --testsuite=stable

 after_failure:
 	- sudo apt-get -qq install gdb
 	- ./unit-tests/ci/after_failure.sh