feathers.lo: /home/odiel/repos/feathers/ext/feathers.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/odiel/repos/feathers/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/odiel/repos/feathers/ext/feathers.c -o feathers.lo 
kernel/main.lo: /home/odiel/repos/feathers/ext/kernel/main.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/odiel/repos/feathers/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/odiel/repos/feathers/ext/kernel/main.c -o kernel/main.lo 
kernel/memory.lo: /home/odiel/repos/feathers/ext/kernel/memory.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/odiel/repos/feathers/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/odiel/repos/feathers/ext/kernel/memory.c -o kernel/memory.lo 
kernel/exception.lo: /home/odiel/repos/feathers/ext/kernel/exception.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/odiel/repos/feathers/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/odiel/repos/feathers/ext/kernel/exception.c -o kernel/exception.lo 
kernel/hash.lo: /home/odiel/repos/feathers/ext/kernel/hash.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/odiel/repos/feathers/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/odiel/repos/feathers/ext/kernel/hash.c -o kernel/hash.lo 
kernel/debug.lo: /home/odiel/repos/feathers/ext/kernel/debug.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/odiel/repos/feathers/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/odiel/repos/feathers/ext/kernel/debug.c -o kernel/debug.lo 
kernel/backtrace.lo: /home/odiel/repos/feathers/ext/kernel/backtrace.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/odiel/repos/feathers/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/odiel/repos/feathers/ext/kernel/backtrace.c -o kernel/backtrace.lo 
kernel/object.lo: /home/odiel/repos/feathers/ext/kernel/object.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/odiel/repos/feathers/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/odiel/repos/feathers/ext/kernel/object.c -o kernel/object.lo 
kernel/array.lo: /home/odiel/repos/feathers/ext/kernel/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/odiel/repos/feathers/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/odiel/repos/feathers/ext/kernel/array.c -o kernel/array.lo 
kernel/extended/array.lo: /home/odiel/repos/feathers/ext/kernel/extended/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/odiel/repos/feathers/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/odiel/repos/feathers/ext/kernel/extended/array.c -o kernel/extended/array.lo 
kernel/string.lo: /home/odiel/repos/feathers/ext/kernel/string.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/odiel/repos/feathers/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/odiel/repos/feathers/ext/kernel/string.c -o kernel/string.lo 
kernel/fcall.lo: /home/odiel/repos/feathers/ext/kernel/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/odiel/repos/feathers/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/odiel/repos/feathers/ext/kernel/fcall.c -o kernel/fcall.lo 
kernel/require.lo: /home/odiel/repos/feathers/ext/kernel/require.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/odiel/repos/feathers/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/odiel/repos/feathers/ext/kernel/require.c -o kernel/require.lo 
kernel/file.lo: /home/odiel/repos/feathers/ext/kernel/file.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/odiel/repos/feathers/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/odiel/repos/feathers/ext/kernel/file.c -o kernel/file.lo 
kernel/operators.lo: /home/odiel/repos/feathers/ext/kernel/operators.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/odiel/repos/feathers/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/odiel/repos/feathers/ext/kernel/operators.c -o kernel/operators.lo 
kernel/concat.lo: /home/odiel/repos/feathers/ext/kernel/concat.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/odiel/repos/feathers/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/odiel/repos/feathers/ext/kernel/concat.c -o kernel/concat.lo 
kernel/variables.lo: /home/odiel/repos/feathers/ext/kernel/variables.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/odiel/repos/feathers/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/odiel/repos/feathers/ext/kernel/variables.c -o kernel/variables.lo 
feathers/http/methods.lo: /home/odiel/repos/feathers/ext/feathers/http/methods.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/odiel/repos/feathers/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/odiel/repos/feathers/ext/feathers/http/methods.c -o feathers/http/methods.lo 
feathers/http/statuscodes.lo: /home/odiel/repos/feathers/ext/feathers/http/statuscodes.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/odiel/repos/feathers/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/odiel/repos/feathers/ext/feathers/http/statuscodes.c -o feathers/http/statuscodes.lo 
feathers/router/destinationinterface.lo: /home/odiel/repos/feathers/ext/feathers/router/destinationinterface.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/odiel/repos/feathers/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/odiel/repos/feathers/ext/feathers/router/destinationinterface.c -o feathers/router/destinationinterface.lo 
feathers/router/route.lo: /home/odiel/repos/feathers/ext/feathers/router/route.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/odiel/repos/feathers/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/odiel/repos/feathers/ext/feathers/router/route.c -o feathers/router/route.lo 
feathers/router/router.lo: /home/odiel/repos/feathers/ext/feathers/router/router.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/odiel/repos/feathers/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/odiel/repos/feathers/ext/feathers/router/router.c -o feathers/router/router.lo 
$(phplibdir)/feathers.la: ./feathers.la
	$(LIBTOOL) --mode=install cp ./feathers.la $(phplibdir)

./feathers.la: $(shared_objects_feathers) $(FEATHERS_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_feathers) $(FEATHERS_SHARED_LIBADD)

